#user container-based infrastructure
os: linux
sudo: required
addons:
  chrome: stable
before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
# install dependencies
install: "pip install -r requirements.txt"
language: python
python:
  - "3.7"
script:
 - robot RedHat_Robot.robot