#user container-based infrastructure
sudo: required
before_install:
  - CDVERSION=`curl http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - echo $CDVERSION
  - wget --no-verbose https://chromedriver.storage.googleapis.com/75.0.3770.90/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sleep 3
  - sudo mv chromedriver /home/travis/build/bartoszstefaniak88/Robot_WSB/
  - sleep 3
# install dependencies
install: "pip install -r requirements.txt"
addons:
  chrome: stable
language: python
python:
  - "3.7"

script:
 - whereis google-chrome-stable
 - whereis chromedriver
 - sleep 3
 - robot RedHat_Robot.robot