#user container-based infrastructure
sudo: false
before_install:
# install dependencies
install: "pip install -r requirements.txt"
language: python
python:
  - "2.7.12"
before_script:
- wget http://chromedriver.storage.googleapis.com/75.0.3770.90/chromedriver_linux64.zip

- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/

- export CHROME_BIN=chromium-browser
script: robot RedHat_Robot.robot