#user container-based infrastructure
sudo: required
before_install:
# install dependencies
install: "pip install -r requirements.txt"
language: python
python:
  - "3.7"
before_script:
- CDVERSION=`curl http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
- echo $CDVERSION
- wget https://chromedriver.storage.googleapis.com/76.0.3809.25/chromedriver_linux64.zip
- unzip chromedriver_linux64.zip
- sudo chmod u+x chromedriver
- sudo mv chromedriver /usr/bin/
script: robot RedHat_Robot.robot