#user container-based infrastructure
os: linux
sudo: required
addons:
  chrome: stable
before_install:
  - wget https://chromedriver.storage.googleapis.com/76.0.3809.126/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/bin/

# install dependencies
install: "pip install -r requirements.txt"
language: python
python:
  - "3.7"
script:
 - robot RedHat_Robot.robot

after_script:
- google-chrome --version
- curl --upload-file ./log.html https://transfer.sh/log.html
- curl --upload-file ./report.html https://transfer.sh/report.html
- curl "https://api.monkeytest.it/travis/test?secret=$MONKEY_KEY&on_load=true&on_click=true&page_weight=true&seo=true&broken_links=true&asset_count=true&url=https://autodemo.testoneo.com"

notifications:
  email:
    recipients:
      - stefaniak88@gmail.com
    on_success: always # default: change
    on_failure: always # default: always