#user container-based infrastructure
os: linux
sudo: required
before_install:
  - wget https://chromedriver.storage.googleapis.com/75.0.3770.90/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sleep 3
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
  - sleep 3
# install dependencies
install: "pip install -r requirements.txt"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: python
python:
  - "3.7"

script:
 - whereis google-chrome-stable
 - whereis chromedriver
 - sleep 3
 - robot RedHat_Robot.robot