#user container-based infrastructure
sudo: required
before_install:
  - CDVERSION=`curl http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - echo $CDVERSION
  - wget --no-verbose https://chromedriver.storage.googleapis.com/75.0.3770.90/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
# install dependencies
install: "pip install -r requirements.txt"
addons:
  chrome: stable
language: python
python:
  - "3.7"

script: robot RedHat_Robot.robot